// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYrPMFMjbmTYT8lmgPbTebAYAn_KuSDk',
    appId: '1:285659528603:web:51f58f629209a706eab53e',
    messagingSenderId: '285659528603',
    projectId: 'barber-pro-new',
    authDomain: 'barber-pro-new.firebaseapp.com',
    storageBucket: 'barber-pro-new.firebasestorage.app',
    measurementId: 'G-FRCQ6HXEZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4dFEp2EYJEZw_Cf_kYc56-nztl7NGz0',
    appId: '1:285659528603:android:7833e07c1c367284eab53e',
    messagingSenderId: '285659528603',
    projectId: 'barber-pro-new',
    storageBucket: 'barber-pro-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFxIR35AbJ9KPvevxFxBsmkcRhWOm0bI',
    appId: '1:285659528603:ios:9530157081589180eab53e',
    messagingSenderId: '285659528603',
    projectId: 'barber-pro-new',
    storageBucket: 'barber-pro-new.firebasestorage.app',
    iosBundleId: 'com.example.barberPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFxIR35AbJ9KPvevxFxBsmkcRhWOm0bI',
    appId: '1:285659528603:ios:9530157081589180eab53e',
    messagingSenderId: '285659528603',
    projectId: 'barber-pro-new',
    storageBucket: 'barber-pro-new.firebasestorage.app',
    iosBundleId: 'com.example.barberPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnYrPMFMjbmTYT8lmgPbTebAYAn_KuSDk',
    appId: '1:285659528603:web:624afce0cd3fbfc3eab53e',
    messagingSenderId: '285659528603',
    projectId: 'barber-pro-new',
    authDomain: 'barber-pro-new.firebaseapp.com',
    storageBucket: 'barber-pro-new.firebasestorage.app',
    measurementId: 'G-QD979VY5LY',
  );
}
